@startuml 401_removeLinkFromPowerSavingActivationQueue
skinparam responseMessageBelowArrow true

title
RequestForRemovingLinkFromPowerSavingActivationQueueCausesQueueUpdate
end title

participant "external" as requestor
participant "AIPS://v1/remove-links-from-power-saving-actication-queue" as removeFromQueue

requestor -> removeFromQueue: {linkId, automationName}
activate removeFromQueue

note over removeFromQueue
  Entries in the SimpleActivationQueue are not unique.
  All instances of the (linkId, automationName) entry must be removed.
end note

deactivate removeFromQueue

@enduml