@startuml 702_providePowerSavingStatusOfLink
skinparam responseMessageBelowArrow true

title
RequestForPowerSavingStatusOfLinkCausesLinkStatusReading
end title

participant "external" as requestor
participant "AIPS://v1/provide-power-saving-status-of-link" as listStatus
participant "ElasticSearch" as es


requestor -> listStatus: {linkId}
activate listStatus

listStatus -> es: {linkId}
es --> listStatus: {list-of(deviationsFromOriginalState), list-of(modulesToRestoreOriginalState)}


listStatus --> requestor: {list-of(deviationsFromOriginalState), list-of(modulesToRestoreOriginalState)}

deactivate listStatus 

@enduml