@startuml 705_cleanupPowerSavingStatusTable.plantuml
skinparam responseMessageBelowArrow true

title
RequestForCleanupOfPowerSavingStatusTableCausesStatusTableCleanup
end title

participant "external" as requestor
participant "AIPS://v1/cleanup-power-saving-status-table" as sync
participant "AIPS://v1/list-links" as listStaticListLinks
participant "ElasticSearch" as es


requestor -> sync
activate sync

'get all linkIds from staticList
note over sync
  <u>GetStaticList</u>
end note
sync -> listStaticListLinks
listStaticListLinks --> sync: {linkIdList}

'get all linkIds from power saving status table
note over sync
  <u>GetPowerSavingStatusTable</u>
end note
sync -> es
es --> sync: {list-of-(linkId, list-of(deviationFromOriginalState))} 

'now cleanup
note over sync
  FOR each linkId from <i>GetPowerSavingStatusTable</i>
    IF (NOT (linkIdList.contains(linkId))
         AND (list-of(deviationFromOriginalState) == emptyList))
    THEN delete record for this linkId from PowerSavingStatus-table
end note

'deactivate sync 
'comment deactivation out, as otherwise activation rectangle ends above the last note box, because there's no response to external


@enduml