@startuml 201_addEndTrigger
skinparam responseMessageBelowArrow true

title
RequestForAddingEndTriggerCausesTimeBasedPowerSavingTriggerUpdate
end title

participant "external" as requestor
participant "AIPS://v1/add-start-trigger" as addTrigger 

requestor -> addTrigger: {time}
activate addTrigger

deactivate addTrigger

@enduml