@startuml 220_syncPowerSavingStatusWithStaticList
skinparam responseMessageBelowArrow true

title
RequestForSyncingStatusTableAndStaticListCausesStatusTableUpdate
end title

participant "external" as requestor
participant "AIPS://v1/sync-power-saving-status-with-static-list" as sync
participant "AIPS://v1/list-links" as listLinks
participant "AIPS://v1/list-power-saving-status" as listStatus
participant "AIPS://v1/delete-link-from-power-saving-status-table" as delete


requestor -> sync
activate sync

== Get StaticList and StatusTable ==
'get staticList
note over sync
  <u>GetStaticList</u>
end note
sync -> listLinks
listLinks -> sync: {linkIdList}

'get powerSavingStatus
note over sync
  <u>GetPowerSavingStatus</u>
end note
sync -> listStatus
listStatus -> sync: {list-of-(linkId, list-of(deviationsFromOriginalState))}

== Delete no longer needed links from StatusTable ==
'remove entries from powerSavingStatus where linkId no longer in staticList
note over sync
  FOR each <i>linkId</i> in GetPowerSavingStatus.response
    IF (GetStaticList.<i>linkIdList</i>.containsNOT(<i>linkId</i>))
      AND (list-of-(deviationsFromOriginalStatus) == emptyList)
    THEN <u>DeleteLinkFromPowerSavingStatus</u>
end note
sync -> delete: {linkId}


deactivate sync

@enduml