@startuml 22x_cyclicOperationOnPowerSavingStatusSync
skinparam responseMessageBelowArrow true

title
RequestForEmbeddingCausesCyclicOperationOnStatusTableAndStaticListSync
end title

participant "external" as requestor
participant "AIPS://v1/embed-yourself" as embed
participant "AIPS://v1/sync-power-saving-status-with-static-list" as sync


requestor -> embed
activate embed

note over embed
  cyclic operation: in configurable intervals the
  powerSavingStatusTable is synchronized
  with the staticList

  <u>StartPowerSavingStatusSync</u>
end note
embed -> sync


deactivate embed

@enduml