@startuml 704_listToBeRestoredLinks
skinparam responseMessageBelowArrow true

title
RequestForListingLinksToBeRestoredCausesStatusTableFiltering
end title

participant "external" as requestor
participant "AIPS://v1/list-to-be-restored-links" as listStatus
participant "ElasticSearch" as es

requestor -> listStatus: {moduleToRestoreOriginalState}
activate listStatus

note over listStatus
  Filter PowerSavingStatus-table for
  records where list-of(modulesToRestoreOriginalState) 
  contains moduleToRestoreOriginalState
end note
listStatus -> es: {moduleToRestoreOriginalState} 
es --> listStatus: {linkIdList}
listStatus --> requestor: {linkIdList}

deactivate listStatus 

@enduml