@startuml 705_deleteLinkFromPowerSavingStatusTable
skinparam responseMessageBelowArrow true

title
RequestForDeletingLinkFromPowerSavingStatusTableCausesDeletionAttempt
end title

participant "external" as requestor
participant "AIPS://v1/delete-link-from-power-saving-status-table" as delete
participant "ElasticSearch" as es

requestor -> delete: {linkId}
activate delete

'get all linkIds from power saving status table
note over delete
  <u>GetPowerSavingStatus</u>
end note
delete -> es: {linkId}
es --> delete: {list-of(deviationsFromOriginalState)} 

note over delete
    IF (deviationsFromOriginalState != emptyList)
    THEN send response
end note
delete --> requestor: {list-of(deviationsFromOriginalState)}, responseCode=204

note over delete #Pink
  ist der responseCode=204 richtig?
  204 = no content
  wir wollen ja aber was zurücksenden
  müsste das nicht in beiden Fällen 200 sein?
  in beiden Fällen wird eine Liste zurückgesendet, in einem Fall ist diese aber leer
  der Aufrufer muss dann anhand der zurückgegebenen Liste entscheiden, wie er das ERgebnis behandelt

  was soll passieren, wenn es den Link in Elastic gar nicht gibt?
end note


'now cleanup
note over delete
    IF (deviationsFromOriginalState == emptyList)
    THEN <u>DeleteLinkFromElasticSearch</u>
end note
delete -> es: {linkId}

delete --> requestor: {}, responseCode=200





deactivate delete 

@enduml