@startuml 510_reactivateAllTransmittersOfLink
skinparam responseMessageBelowArrow true

title
RequestForReactivatingAllTransmittersOfLinkInitiatesTransaction
end title

participant "REQUESTOR" as requestor
participant "e.g. AIPS://v1/receive-power-saving-deactivation-status" as delivery
participant "AIPS://v1/reactivate-all-transmitters-of-link" as ato
participant "AIPS://v1/provide-power-saving-status-of-link" as readStatus
participant "MWDI://core-model-1-4:network-control-domain=cache/link={uuid}" as resolveAddress
participant "MWDG://core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-configuration/transmitter-is-on" as mwdg
participant "AIPS://v1/record-power-saving-status" as recordStatus
'participant "AIPS://<alarm-service-to-be-specified>" as alarm

requestor -> ato: {linkId, automationName, own_IpAddress, own_TcpPort, /v1/receive-power-saving-deactivation-status}
activate ato
ato --> requestor: {requestId}

== Get power saving status ==

note over ato
  <u>ReadPowerSavingStatusOfLink</u>
end note
ato -> readStatus: {linkId}
readStatus -> ato: {deviationsFromOriginalState, modulesToRestoreOriginalState}

note over ato
  IF (modulesToRestoreOriginalState does NOT contain "AllTransmittersOn")
  THEN <u>Response</u> and exit
end note
ato -> delivery: {requestId, statusOfLink="NotQualified"}

== Link qualified: try transmitter switch-on ==

note over ato
  ELSE <u>DetermineLinkEndpoints</u> of initial Link
end note
ato -> resolveAddress: {uuid=linkId}
resolveAddress --> ato: {2x(CC,LTP,LP)}

note over ato
  For both link endpoints 
  <u>SwitchTransmitters<b>On</b></u>
end note
ato -> mwdg: {mountName-from-CC, uuid-from-LTP, localId-from-LP}
mwdg --> ato: {odlResponseCode}

note over ato
  IF (both odlResponseCode of SwitchTransmitters<b>On</b> == 204)
    THEN <u>Response</u> and <u>ReportPowerSavingStatus</u> and exit
end note 
ato -> recordStatus: {linkId, removeDeviationsFromOriginalState="RedundantTransmittersOff", removeModulesToRestoreOriginalState="AllTransmittersOn"}
ato -> delivery: {requestId, statusOfLink="AllTransmittersOn"}

== Transmitter switch-on failed: try rollback ==

note over ato
  IF (at least one odlResponseCode of SwitchTransmitters<b>On</b> != 204)
    THEN <u>SwitchBothTransmitters<b>Off</b></u>
end note
ato -> mwdg: {mountName-from-CC, uuid-from-LTP, localId-from-LP}
mwdg --> ato: {odlResponseCode}

note over ato
  IF (both odlResponseCode of SwitchTransmitters<b>Off</b> == 204))
    THEN <u>Response</u> and <u>ReportPowerSavingStatus</u> and exit
end note
ato -> recordStatus: {linkId, addDeviationsFromOriginalState="RedundantTransmittersOff", addModulesToRestoreOriginalState="AllTransmittersOn"}
ato -> delivery: {requestId, statusOfLink="RedundantTransmittersOff"}

== Rollback also failed: UndefinedState ==

'alarms to be added with later release version
'note over ato
'  IF (at least one responseCode of SwitchTransmitters<b>On</b> != 200)
'      AND (at least one responseCode of SwitchTransmitters<b>Off</b> != 200))
'  THEN <u>ReportAlarm</u> and <u>Response</u>
'end note 
'ato -> alarm: {<i>to be specified</i>}


note over ato
  ELSE <u>ReportPowerSavingStatus</u> and <u>Response</u>
end note 
ato -> recordStatus: {linkId, addModulesToRestoreOriginalState="AllTransmittersOn"}
ato -> delivery: {requestId, statusOfLink="UndefinedState"}


deactivate ato 

@enduml