@startuml 301_stopDroppedFramesMonitoring
skinparam responseMessageBelowArrow true

title
RequestForStoppingDroppedFramesMonitoringCausesTurningOffDroppedFramesMonitoringModule
end title

participant "external" as requestor
participant "AIPS://v1/stop-dropped-frames-monitoring" as stopModule

requestor -> stopModule
activate stopModule

note over stopModule
  was soll gemacht werden?
  - sollen alle power savings wieder eingeschaltet werden, die wegen droppedFrames augeschaltet wurden?
    (bzw. man ruft die Einschalt-Services auf, die dann erstmal prüfen, ob die Bedingungen überhaupt noch erfüllt sind)
  - oder wird einfach nur die cyclicOperation von startDroppedFramesMonitoring gestoppt?
    (da hätte man ja dann eignetlich gar keinen Service-Aufruf...)  
end note

deactivate stopModule

@enduml