@startuml 01x_Embedding
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCauses...
end title

participant "RO" as RO
participant "AIPS://v1/embed-yourself" as AIPS

RO -> AIPS
activate AIPS

note over AIPS
No individual embedding steps identified
end note

deactivate AIPS

@enduml